const ADD_SITE = "ADD_SITE";
const DELETE_SITE = "DELETE_SITE";
const SHOW_RIGHT_DRAWER = "SHOW_RIGHT_DRAWER";
const CLOSE_RIGHT_DRAWER = "CLOSE_RIGHT_DRAWER";
const PREVIEW_ICON = "PREVIEW_ICON";
const SELECT_RADIO = "SELECT_RADIO";
const OPEN_COLOR_PICKER = "OPEN_COLOR_PICKER";
const CLOSE_COLOR_PICKER = "CLOSE_COLOR_PICKER";
const PICK_ONE_COLOR = "PICK_ONE_COLOR";

export {
  ADD_SITE,
  DELETE_SITE,
  SHOW_RIGHT_DRAWER,
  CLOSE_RIGHT_DRAWER,
  PREVIEW_ICON,
  SELECT_RADIO,
  OPEN_COLOR_PICKER,
  CLOSE_COLOR_PICKER,
  PICK_ONE_COLOR
};
