const ADD_SITE = "ADD_SITE";
const DELETE_SITE = "DELETE_SITE";
const SHOW_RIGHT_DRAWER = "SHOW_RIGHT_DRAWER";
const CLOSE_RIGHT_DRAWER = "CLOSE_RIGHT_DRAWER";
const PREVIEW_ICON = "PREVIEW_ICON";

export {
  ADD_SITE,
  DELETE_SITE,
  SHOW_RIGHT_DRAWER,
  CLOSE_RIGHT_DRAWER,
  PREVIEW_ICON
};
