const ADD_SITE = 'ADD_SITE'
const DELETE_SITE = 'DELETE_SITE'
const SHOW_SITE_FORM = 'SHOW_SITE_FORM'
const CLOSE_SITE_FORM = 'CLOSE_SITE_FORM'

export {
  ADD_SITE,
  DELETE_SITE,
  SHOW_SITE_FORM,
  CLOSE_SITE_FORM
}
